### ISSUE TITLE
Private repo support

### ISSUE THREAD

**Issue by dbollaer** [cirrusidentity/docker-simplesamlphp#8]
### Summary
Thank you for the great work on this project! We are currently using SimpleSAMLphp and are considering migrating to your Docker image.

### Issue
Our existing setup involves additional private modules hosted on our private GitHub repositories. We would like to know if your Docker image supports loading from private repositories, or if there's a plan to support it in the future.

### Proposal
If there's no existing support for loading private GitHub repositories, I'm willing to help by submitting a pull request to add this feature. Could you provide some guidance on the best approach to implement this functionality? I'm interested in learning how you'd prefer it to be implemented so I can align with your project's structure and conventions.

### Additional Information
I plan to start working on this in the next couple of weeks, so any early guidance would be helpful. I look forward to hearing from you.

### Thank You
Thanks again for your time and assistance. I appreciate your dedication to this project and look forward to contributing.

Best regards,
Danny

**Comment by pradtke** [comment]
Hi @dbollaer ,

This image takes the approach of including lots of stuff that might be needed for doing testing. 
I think if you are going to create an image for your production systems you should use a leaner image without all the extras. For example if you don't use a database there is no need to have the `pdo` stuff installed. There are number of things in that category, including `ldap`, `memcached`.

The ways we've explored doing private repos, you can either use `ssh` socket or a github token.  During your docker build you would pass `--ssh default=$SSH_AUTH_SOCK` to let the build have access to your ssh context, and then we do stuff like below to tell the build to make ssh stuff available to the composer command and to persist the composer cache across different builds

```
RUN --mount=type=ssh \
    --mount=type=cache,target=/tmp/cache/composer,mode=0777 \
    other composer commands to add repos, install etc,
```

We haven't looked at how to pull down private repos at runtime (since we do it in our builds).  My guess is if you want to pull some private repos in at run time is maybe change `ssp-startup.sh` to call a script `ssp-startup-extension.sh` as the first thing. That script does nothing by default.   In your case, you can mount your own version that adds repositories to the composer config, sets `composer config -g github-oauth.github.com secret` if that is how you auth, etc.
I'm thinking this provides an extension point for runtime commands without caring about use case.  I'm open to something more specific for private repos, however I'm not sure to make it generic across potential use cases.

**Comment by dbollaer** [comment]
Hi @pradtke,
Thank you for your help.  I ll try to solve it first using your way and discuss it with my colleagues.
